platform :ios, '5.0'
pod 'Parse', '~> 1.2.6'
pod 'Facebook-iOS-SDK', '~> 3.5.0'
pod 'AKSegmentedControl', '~> 1.0.2'
pod 'KGStatusBar', '~> 1.0'
pod 'PRTween', '~> 0.0.1'
pod 'MCSwipeTableViewCell', '~> 1.0.0'
pod 'UAModalPanel', '~> 1.1.1'
pod 'MagicalRecord', '~> 2.1'