platform :ios, '5.0'
pod 'Appirater', '~> 1.0.3'
pod 'Parse', '~> 1.2.13'
pod 'Facebook-iOS-SDK', '~> 3.7.1'
pod 'KGStatusBar', '~> 1.0'
pod 'PRTween', '~> 0.0.1'
pod 'MagicalRecord', '~> 2.2'
pod 'Mixpanel', '~> 2.0.0'
pod 'SMPageControl', '~> 1.0'
